name: My Custom Action

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: 24f3004572@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
        
      - name: Another step
        run: echo "Action completed successfully"
